export const DEFINITION= {
    CURRENT_USER:"CURRENT_USER",
    SPLASH_SCREEN:'SPLASH_SCREEN',
    USER_UID:'USER_UID',
    LOGGED_IN:'LOGGED_IN',
    ALL_NOTES:'ALL_NOTES',
    SETTINGS:'SETTINGS',
    MY_NOTES:"MY_NOTES"
}
